import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <nav className="flex content-between w-full mb-8">
          <div className="flex flex-1 justify-center align-center">
            img-Notrito
          </div>
          <div className="flex flex-auto justify-center align-center">
            <a className="mr-2 text-green-600">ACASA</a>
            <a className="mr-2 text-green-500">CUM FUNCTIONEAZA</a>
            <a className="mr-2 text-green-500">BENEFICII</a>
            <a className="mr-2 text-green-500">PLANURI</a>
            <a className="text-green-500">CONTACT</a>
          </div>
          <div className="flex flex-1 justify-center align-center">
            <button>LOGIN</button>
          </div>
        </nav>

        <div>
          <h1 className="flex justify-center text-green-600 text-5xl tracking-widest">
            Calculeaza rapid si usor
          </h1>
          <h1 className="flex justify-center text-green-600 text-5xl tracking-widest">
            valorile nutritionale
          </h1>
        </div>

        <div className="flex justify-center items-center w-full mt-8">
          <div className="flex justify-center flex-col text-center border border-solid border-stone-200 h-40 p-4 w-36">
            <p className="text-green-500">OBTINE RAPID</p>
            <div className="py-3">img 1</div>
          </div>

          <div className="flex justify-center items-center text-center flex-col border border-solid border-stone-200 h-40 p-4 mx-8 w-36">
            <p className="text-green-500">INFORMATII</p>
            <div className="py-3">img 2</div>
          </div>

          <div className="flex justify-center items-center text-center flex-col border border-solid border-stone-200 h-40 p-4 h-40 w-36">
            <p className="text-green-500">PENTRU PRODUSELE TALE</p>
            <div className="py-3">img 3</div>
          </div>
        </div>
      </main>
    </>
  );
}
